#!/bin/bash
sudo apt install vim tmux ack -y

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

npm i -g typescript typescript-language-server
