#!/bin/bash
sudo apt install vim tmux ack -y

git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim
git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

npm i -g typescript typescript-language-server

# Install python3 support for neovim (for allow vim-ai)
pip3 install --user --break-system-packages pynvim
