"Autogenerated .vimrc entries
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

set rtp+=~/.fzf
Plugin 'VundleVim/Vundle.vim'
Plugin 'elixir-editors/vim-elixir'
Plugin 'mhinz/vim-mix-format'
Plugin 'itchyny/lightline.vim'
Plugin 'altercation/vim-colors-solarized'
Plugin 'junegunn/fzf'
Plugin 'junegunn/fzf.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'leafgarland/typescript-vim'
Plugin 'elmcast/elm-vim'
Plugin 'tpope/vim-commentary'
Plugin 'hashivim/vim-terraform'
"Plugin 'dense-analysis/ale'

call vundle#end()

inoremap jj <ESC>

syntax on
filetype plugin indent on
set laststatus=2
set statusline+=%#warningmsg#
set statusline+=%*
set expandtab
set shiftwidth=2
set softtabstop=2
set autowrite
set autoread
set incsearch
set nocompatible
set number
set ttyfast
set hlsearch
set laststatus=2
set noshowmode

set t_Co=256
syntax enable
set background=dark
let g:solarized_termcolors=256
let g:solarized_termtrans=1
colorscheme solarized

let g:lightline = { 'colorscheme': 'solarized'}
let g:lightline = {
      \   'component_function': {
      \     'filename': 'LightLineFilename'
      \   },
      \   'colorscheme': 'solarized'
      \ }
function! LightLineFilename()
  return expand('%')
endfunction

set omnifunc=syntaxcomplete#Complete
set wildignore+=*/node_modules/*,*/deps/*,*/tmp/*,*.so,*.swp,*.zip
noremap <C-p> :Files<cr>

let $BASH_ENV = "~/.bash_aliases"
let $FZF_DEFAULT_COMMAND = '(gitls || gitlsdirs | ack "") || ack -g ""'

"Remove spaces at the end of lines
autocmd BufWritePre * %s/\s\+$//e

autocmd BufWritePost * doautocmd Syntax
autocmd BufReadPost * doautocmd Syntax

silent !mkdir -p ~/.vim/undo
set undofile
set undodir=~/.vim/undo
let s:undos = split(globpath(&undodir, '*'), "\n")
call filter(s:undos, 'getftime(v:val) < localtime() - (60 * 60 * 24 * 90)')
call map(s:undos, 'delete(v:val)')

set iskeyword+=-

au BufRead,BufNewFile *.ex* set filetype=elixir
au BufRead,BufNewFile *.elm set filetype=elm
au BufRead,BufNewFile *.html.*eex set filetype=eelixir

let g:mix_format_on_save = 1
" let g:mix_format_silent_errors = 1

" autocmd BufWritePre <buffer> silent update %!mix format -

" let g:ale_elixir_elixir_ls_release = '/projects/elixir-ls/rel'
" let g:ale_linters = {'elixir': ['elixir-ls']}

" ==Terraform==
au BufRead,BufNewFile *.tf* set filetype=terraform
let g:terraform_align=1
let g:terraform_fmt_on_save=1

" Disable continuing comments on a new line
set formatoptions-=cro
